// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlrqteuikhwsnfasrloa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpscnF0ZXVpa2h3c25mYXNybG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3ODY5MzYsImV4cCI6MjA4ODM2MjkzNn0.pWTuON7sK7BIADoaqfKwYVHvcr4D1ShNlvg0vm6Wo9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});